version: '3.8'
services:
    postgres:
        container_name: postgres_my_resume
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: mydatabase
        ports:
            - '5432:5432'
    pgadmin:
        container_name: pgadmin_my_resume
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - '5050:80'
